# Generated by Django 3.0.3 on 2020-02-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Company Index')),
                ('company', models.CharField(blank=True, max_length=128, null=True, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('_id', models.CharField(max_length=128, unique=True, verbose_name='People ID')),
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='People Index')),
                ('guid', models.CharField(max_length=128, unique=True, verbose_name='GUID')),
                ('has_died', models.BooleanField(default=False, verbose_name='Died')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=32, verbose_name='Balance')),
                ('picture', models.CharField(blank=True, max_length=256, null=True, verbose_name='Picture')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age')),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True, verbose_name='Eye Color')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('gender', models.CharField(blank=True, max_length=16, null=True, verbose_name='Gender')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('registered', models.DateTimeField(blank=True, null=True, verbose_name='Registered')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Tags')),
                ('favourite_food', models.TextField(blank=True, null=True, verbose_name='Favourite Food')),
                ('fruits', models.TextField(blank=True, null=True, verbose_name='Favourite Fruit')),
                ('vegetables', models.TextField(blank=True, null=True, verbose_name='Favourite Vegetable')),
                ('greeting', models.TextField(blank=True, null=True, verbose_name='Greeting')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='paranuara.Company', verbose_name='Company ID')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paranuara.People', verbose_name='Friend')),
                ('people_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='paranuara.People', verbose_name='People')),
            ],
        ),
    ]
